baseURL = "http://example.org/"

# æ›´æ”¹ä½¿ç”¨ Hugo æ„å»ºç½‘ç«™æ—¶ä½¿ç”¨çš„é»˜è®¤ä¸»é¢˜
theme = "FixIt"

# ç½‘ç«™æ ‡é¢˜
title = "Deequoique's èµ›åšå°å±‹"

# ç½‘ç«™è¯­è¨€, ä»…åœ¨è¿™é‡Œ CN å¤§å†™ ["en", "zh-CN", "fr", "pl", ...]
languageCode = "zh-CN"
# è¯­è¨€åç§° ["English", "ç®€ä½“ä¸­æ–‡", "FranÃ§ais", "Polski", ...]
languageName = "ç®€ä½“ä¸­æ–‡"
# æ˜¯å¦åŒ…æ‹¬ä¸­æ—¥éŸ©æ–‡å­—
hasCJKLanguage = true

# è°·æ­Œåˆ†æä»£å· [UA-XXXXXXXX-X]
googleAnalytics = ""
# ç‰ˆæƒæè¿°ï¼Œä»…ä»…ç”¨äº SEO
copyright = ""

# æ˜¯å¦ä½¿ç”¨ robots.txt
enableRobotsTXT = true
# æ˜¯å¦ä½¿ç”¨ git ä¿¡æ¯
enableGitInfo = false
# æ˜¯å¦ä½¿ç”¨ emoji ä»£ç 
enableEmoji = true

# å¿½ç•¥ä¸€äº›æ„å»ºé”™è¯¯
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

# èœå•é…ç½®
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    # ä½ å¯ä»¥åœ¨åç§° (å…è®¸ HTML æ ¼å¼) ä¹‹å‰æ·»åŠ å…¶ä»–ä¿¡æ¯, ä¾‹å¦‚å›¾æ ‡
    pre = ""
    # ä½ å¯ä»¥åœ¨åç§° (å…è®¸ HTML æ ¼å¼) ä¹‹åæ·»åŠ å…¶ä»–ä¿¡æ¯, ä¾‹å¦‚å›¾æ ‡
    post = ""
    name = "å…¨éƒ¨"
    url = "/posts/"
    # å½“ä½ å°†é¼ æ ‡æ‚¬åœåœ¨æ­¤èœå•é“¾æ¥ä¸Šæ—¶, å°†æ˜¾ç¤ºçš„æ ‡é¢˜
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "tags"
    pre = ""
    post = ""
    name = "æ ‡ç­¾"
    url = "/tags/"
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "categories"
    pre = ""
    post = ""
    name = "åˆ†ç±»"
    url = "/categories/"
    title = ""
  [[menu.main]]
    weight = 4
    identifier = "friends"
    pre = ""
    post = ""
    name = "å‹é“¾"
    url = "/friends/"
    title = ""
[module]
  [module.hugoVersion]
    extended = true
    min = "0.132.0"

[params]
  # ç½‘ç«™é»˜è®¤ä¸»é¢˜æ ·å¼ ["auto", "light", "dark"]
  defaultTheme = "auto"
  # å…¬å…± git ä»“åº“è·¯å¾„ï¼Œä»…åœ¨ enableGitInfo è®¾ä¸º true æ—¶æœ‰æ•ˆ
  gitRepo = ""
  #  å“ªç§å“ˆå¸Œå‡½æ•°ç”¨æ¥ SRI, ä¸ºç©ºæ—¶è¡¨ç¤ºä¸ä½¿ç”¨ SRI
  # ["sha256", "sha384", "sha512", "md5"]
  fingerprint = ""
  #  æ—¥æœŸæ ¼å¼
  dateFormat = "2006-01-02"
  # ç½‘ç«™æ ‡é¢˜, ç”¨äº Open Graph å’Œ Twitter Cards
  title = "Deequoique's èµ›åšå°å±‹"
  # ç½‘ç«™æè¿°, ç”¨äº RSS, SEO, Open Graph å’Œ Twitter Cards
  description = "Deequoique's èµ›åšå°å±‹"
  # ç½‘ç«™å›¾ç‰‡, ç”¨äº Open Graph å’Œ Twitter Cards
  images = ["/logo.png"]
# ä½œè€…é…ç½®
  [params.author]
  name = "Deequoique"
  email = "javawangtl@163.com"
  link = "/"
  # é¡µé¢å¤´éƒ¨å¯¼èˆªæ é…ç½®
  [params.header]
    # æ¡Œé¢ç«¯å¯¼èˆªæ æ¨¡å¼ ["fixed", "normal", "auto"]
    desktopMode = "sticky"
    # ç§»åŠ¨ç«¯å¯¼èˆªæ æ¨¡å¼ ["fixed", "normal", "auto"]
    mobileMode = "auto"
    #  é¡µé¢å¤´éƒ¨å¯¼èˆªæ æ ‡é¢˜é…ç½®
    [params.header.title]
      # LOGO çš„ URL
      logo = ""
      # æ ‡é¢˜åç§°
      name = "ğŸŸå–œæ¬¢æ‚¨æ¥"
      # ä½ å¯ä»¥åœ¨åç§° (å…è®¸ HTML æ ¼å¼) ä¹‹å‰æ·»åŠ å…¶ä»–ä¿¡æ¯, ä¾‹å¦‚å›¾æ ‡
      pre = ""
      # ä½ å¯ä»¥åœ¨åç§° (å…è®¸ HTML æ ¼å¼) ä¹‹åæ·»åŠ å…¶ä»–ä¿¡æ¯, ä¾‹å¦‚å›¾æ ‡
      post = ""
      #  æ˜¯å¦ä¸ºæ ‡é¢˜æ˜¾ç¤ºæ‰“å­—æœºåŠ¨ç”»
      typeit = false

  # é¡µé¢åº•éƒ¨ä¿¡æ¯é…ç½®
  [params.footer]
    enable = true
    #  è‡ªå®šä¹‰å†…å®¹ (æ”¯æŒ HTML æ ¼å¼)
    custom = ''
    #  æ˜¯å¦æ˜¾ç¤º Hugo å’Œä¸»é¢˜ä¿¡æ¯
    hugo = true
    #  æ˜¯å¦æ˜¾ç¤ºç‰ˆæƒä¿¡æ¯
    copyright = true
    #  æ˜¯å¦æ˜¾ç¤ºä½œè€…
    author = true
    # ç½‘ç«™åˆ›ç«‹å¹´ä»½
    since = 2023
    # ICP å¤‡æ¡ˆä¿¡æ¯ï¼Œä»…åœ¨ä¸­å›½ä½¿ç”¨ (æ”¯æŒ HTML æ ¼å¼)
    icp = ""
    # è®¸å¯åè®®ä¿¡æ¯ (æ”¯æŒ HTML æ ¼å¼)
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
    
    [params.footer.siteTime]
      enable = true
      animate = true
      icon = "fa-solid fa-heartbeat"
      pre = ""
      value = "2023-12-21T17:35:44+08:00"
  
  #  Section (æ‰€æœ‰æ–‡ç« ) é¡µé¢é…ç½®
  [params.section]
    # section é¡µé¢æ¯é¡µæ˜¾ç¤ºæ–‡ç« æ•°é‡
    paginate = 20
    # æ—¥æœŸæ ¼å¼ (æœˆå’Œæ—¥)
    dateFormat = "01-02"
    # RSS æ–‡ç« æ•°ç›®
    rss = 10

  #  List (ç›®å½•æˆ–æ ‡ç­¾) é¡µé¢é…ç½®
  [params.list]
    # list é¡µé¢æ¯é¡µæ˜¾ç¤ºæ–‡ç« æ•°é‡
    paginate = 20
    # æ—¥æœŸæ ¼å¼ (æœˆå’Œæ—¥)
    dateFormat = "01-02"
    # RSS æ–‡ç« æ•°ç›®
    rss = 10

  #  åº”ç”¨å›¾æ ‡é…ç½®
  [params.app]
    # å½“æ·»åŠ åˆ° iOS ä¸»å±å¹•æˆ–è€… Android å¯åŠ¨å™¨æ—¶çš„æ ‡é¢˜, è¦†ç›–é»˜è®¤æ ‡é¢˜
    title = "æˆ‘çš„ç½‘ç«™"
    # æ˜¯å¦éšè—ç½‘ç«™å›¾æ ‡èµ„æºé“¾æ¥
    noFavicon = false
    # æ›´ç°ä»£çš„ SVG ç½‘ç«™å›¾æ ‡, å¯æ›¿ä»£æ—§çš„ .png å’Œ .ico æ–‡ä»¶
    svgFavicon = "/logo.png"
    # Android æµè§ˆå™¨ä¸»é¢˜è‰²
    themeColor = "#ffffff"
    # Safari å›¾æ ‡é¢œè‰²
    iconColor = "#5bbad5"
    # Windows v8-10ç£è´´é¢œè‰²
    tileColor = "#da532c"

  #  æœç´¢é…ç½®
  [params.search]
    enable = true
    type = "fuse"
    contentLength = 4000
    placeholder = ""
    maxResultLength = 10
    snippetLength = 30
    highlightTag = "em"
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""
    [params.search.fuse]
      isCaseSensitive = false
      minMatchCharLength = 2
      findAllMatches = false
      location = 0
      threshold = 0.3
      distance = 100
      ignoreLocation = false
      useExtendedSearch = false
      ignoreFieldNorm = false

  # ä¸»é¡µé…ç½®
  [params.home]
    #  RSS æ–‡ç« æ•°ç›®
    rss = 10
    # ä¸»é¡µä¸ªäººä¿¡æ¯
    [params.home.profile]
      enable = true
      # Gravatar é‚®ç®±ï¼Œç”¨äºä¼˜å…ˆåœ¨ä¸»é¡µæ˜¾ç¤ºçš„å¤´åƒ
      gravatarEmail = ""
      # ä¸»é¡µæ˜¾ç¤ºå¤´åƒçš„ URL
      avatarURL = "/logo.png"
      #  ä¸»é¡µæ˜¾ç¤ºçš„ç½‘ç«™æ ‡é¢˜ (æ”¯æŒ HTML æ ¼å¼)
      title = "Deequoique's èµ›åšå°å±‹"
      # ä¸»é¡µæ˜¾ç¤ºçš„ç½‘ç«™å‰¯æ ‡é¢˜ (å…è®¸ HTML æ ¼å¼)
      subtitle = "ğŸ’»JAVA/web3/Godot<br>âš ï¸è‡ªç”±çš„äºšæ–‡åŒ–/æ€§å‘/xpè¯·è‡ªè¡Œé¿é›·<br>â¤ï¸â€ğŸ”¥ç±»å‹å­¦/æ°‘å“²/ç”µå‰ä»–<br>ğŸ®pc/switchğŸ²coc<br>ãŠ™ï¸ç‹¬æ¸¸æ‘¸é±¼å¼€å‘è€…"
      # æ˜¯å¦ä¸ºå‰¯æ ‡é¢˜æ˜¾ç¤ºæ‰“å­—æœºåŠ¨ç”»
      typeit = true
      # æ˜¯å¦æ˜¾ç¤ºç¤¾äº¤è´¦å·
      social = true
      #  å…è´£å£°æ˜ (æ”¯æŒ HTML æ ¼å¼)
      disclaimer = ""
    # ä¸»é¡µæ–‡ç« åˆ—è¡¨
    [params.home.posts]
      enable = true
      # ä¸»é¡µæ¯é¡µæ˜¾ç¤ºæ–‡ç« æ•°é‡
      paginate = 6

  # ä½œè€…çš„ç¤¾äº¤ä¿¡æ¯è®¾ç½®
  [params.social]
   Email = "puppy_road@163.com"
   github = "deequoique"
   bilibili = "3546645719419634"

  # æµè§ˆç»Ÿè®¡
  [params.busuanzi]
    enable = true
    source = "https://vercount.one/js"
    siteViews = true
    pageViews = true

  #  æ–‡ç« é¡µé¢å…¨å±€é…ç½®
  [params.page]
    #  æ˜¯å¦åœ¨ä¸»é¡µéšè—ä¸€ç¯‡æ–‡ç« 
    hiddenFromHomePage = false
    #  æ˜¯å¦åœ¨æœç´¢ç»“æœä¸­éšè—ä¸€ç¯‡æ–‡ç« 
    hiddenFromSearch = false
    #  æ˜¯å¦ä½¿ç”¨ twemoji
    twemoji = true
    # æ˜¯å¦ä½¿ç”¨ lightgallery
    lightgallery = true
    #  æ˜¯å¦ä½¿ç”¨ ruby æ‰©å±•è¯­æ³•
    ruby = true
    #  æ˜¯å¦ä½¿ç”¨ fraction æ‰©å±•è¯­æ³•
    fraction = true
    #  æ˜¯å¦ä½¿ç”¨ fontawesome æ‰©å±•è¯­æ³•
    fontawesome = true
    # æ˜¯å¦åœ¨æ–‡ç« é¡µé¢æ˜¾ç¤ºåŸå§‹ Markdown æ–‡æ¡£é“¾æ¥
    linkToMarkdown = true
    #  æ˜¯å¦åœ¨ RSS ä¸­æ˜¾ç¤ºå…¨æ–‡å†…å®¹
    rssFullText = false
    # FixIt 0.2.17 | æ›´æ”¹ å¼€å¯è‡ªåŠ¨ä¹¦ç­¾æ”¯æŒ
    # å¦‚æœä¸º trueï¼Œåˆ™åœ¨å…³é—­é¡µé¢æ—¶ä¿å­˜é˜…è¯»è¿›åº¦
    autoBookmark = false
    # FixIt 0.2.17 | æ–°å¢ æ˜¯å¦ä½¿ç”¨ å­—æ•°ç»Ÿè®¡
    wordCount = true
    # FixIt 0.2.17 | æ–°å¢ æ˜¯å¦ä½¿ç”¨ é¢„è®¡é˜…è¯»
    readingTime = true
    # FixIt 0.2.18 | æ–°å¢ æ˜¯å¦å¼€å¯å³æ—¶é¡µé¢
    instantPage = true
  # FixIt 0.3.0 | æ–°å¢ æ˜¯å¦åœ¨ä¾§è¾¹æ æ˜¾ç¤ºé›†åˆåˆ—è¡¨
    collectionList = false
    # FixIt 0.3.0 | æ–°å¢ æ˜¯å¦åœ¨æ–‡ç« æœ«å°¾æ˜¾ç¤ºé›†åˆå¯¼èˆª
    collectionNavigation = false
    #  ç›®å½•é…ç½®
    [params.page.toc]
      # æ˜¯å¦ä½¿ç”¨ç›®å½•
      enable = true
      #  æ˜¯å¦ä¿æŒä½¿ç”¨æ–‡ç« å‰é¢çš„é™æ€ç›®å½•
      keepStatic = false
      # æ˜¯å¦ä½¿ä¾§è¾¹ç›®å½•è‡ªåŠ¨æŠ˜å å±•å¼€
      auto = false
    #  ä»£ç é…ç½®
    [params.page.code]
      # æ˜¯å¦æ˜¾ç¤ºä»£ç å—çš„å¤åˆ¶æŒ‰é’®
      copy = true
      # é»˜è®¤å±•å¼€æ˜¾ç¤ºçš„ä»£ç è¡Œæ•°
      maxShownLines = 50
    #  KaTeX æ•°å­¦å…¬å¼
    [params.page.math]
      enable = true
      #  é»˜è®¤è¡Œå†…å®šç•Œç¬¦æ˜¯ $ ... $ å’Œ \( ... \)
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      #  é»˜è®¤å—å®šç•Œç¬¦æ˜¯ $$ ... $$, \[ ... \],  \begin{equation} ... \end{equation} å’Œä¸€äº›å…¶å®ƒçš„å‡½æ•°
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      # KaTeX æ’ä»¶ copy_tex
      copyTex = true
      # KaTeX æ’ä»¶ mhchem
      mhchem = true
    #  Mapbox GL JS é…ç½®
    [params.page.mapbox]
      # Mapbox GL JS çš„ access token
      accessToken = ""
      # æµ…è‰²ä¸»é¢˜çš„åœ°å›¾æ ·å¼
      lightStyle = "mapbox://styles/mapbox/light-v10?optimize=true"
      # æ·±è‰²ä¸»é¢˜çš„åœ°å›¾æ ·å¼
      darkStyle = "mapbox://styles/mapbox/dark-v10?optimize=true"
      # æ˜¯å¦æ·»åŠ  NavigationControl
      navigation = true
      # æ˜¯å¦æ·»åŠ  GeolocateControl
      geolocate = true
      # æ˜¯å¦æ·»åŠ  ScaleControl
      scale = true
      # æ˜¯å¦æ·»åŠ  FullscreenControl
      fullscreen = true
    #  æ–‡ç« é¡µé¢çš„åˆ†äº«ä¿¡æ¯è®¾ç½®
    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = false
      Whatsapp = false
      Pinterest = false
      Tumblr = false
      HackerNews = false
      Reddit = false
      VK = false
      Buffer = false
      Xing = false
      Line = false
      Instapaper = false
      Pocket = false
      Flipboard = false
      Weibo = true
      Blogger = false
      Baidu = false
      Odnoklassniki = false
      Evernote = false
      Skype = false
      Trello = false
      Mix = false
    #  è¯„è®ºç³»ç»Ÿè®¾ç½®
    [params.page.comment]
      enable = true
      # Disqus è¯„è®ºç³»ç»Ÿè®¾ç½®
      [params.page.comment.disqus]
        # 
        enable = false
        # Disqus çš„ shortnameï¼Œç”¨æ¥åœ¨æ–‡ç« ä¸­å¯ç”¨ Disqus è¯„è®ºç³»ç»Ÿ
        shortname = ""
      # Gitalk è¯„è®ºç³»ç»Ÿè®¾ç½®
      [params.page.comment.gitalk]
        # 
        enable = false
        owner = ""
        repo = ""
        clientId = ""
        clientSecret = ""
      # Valine è¯„è®ºç³»ç»Ÿè®¾ç½®
      [params.page.comment.valine]
        enable = false
        appId = "xXp7hKZAdBhGdTXs3ridbfNY-MdYXbMMI"
        appKey = "CCGEhKR69Acc24jPraVHu1Mq"
        placeholder = "å¤šè¯´è¯´å¤šè¯´è¯´ï½"
        avatar = "mp"
        meta= ""
        pageSize = 10
        # ä¸ºç©ºæ—¶è‡ªåŠ¨é€‚é…å½“å‰ä¸»é¢˜ i18n é…ç½®
        lang = ""
        visitor = true
        recordIP = false
        highlight = true
        enableQQ = true
        serverURLs = "https://xxp7hkza.api.lncldglobal.com"
        #  emoji æ•°æ®æ–‡ä»¶åç§°, é»˜è®¤æ˜¯ "google.yml"
        # ["apple.yml", "google.yml", "facebook.yml", "twitter.yml"]
        # ä½äº "themes/LoveIt/assets/lib/valine/emoji/" ç›®å½•
        # å¯ä»¥åœ¨ä½ çš„é¡¹ç›®ä¸‹ç›¸åŒè·¯å¾„å­˜æ”¾ä½ è‡ªå·±çš„æ•°æ®æ–‡ä»¶:
        # "assets/lib/valine/emoji/"
        emoji = ""
      # Facebook è¯„è®ºç³»ç»Ÿè®¾ç½®
      [params.page.comment.facebook]
        enable = false
        width = "100%"
        numPosts = 10
        appId = ""
        # ä¸ºç©ºæ—¶è‡ªåŠ¨é€‚é…å½“å‰ä¸»é¢˜ i18n é…ç½®
        languageCode = "zh_CN"
      #  Telegram Comments è¯„è®ºç³»ç»Ÿè®¾ç½®
      [params.page.comment.telegram]
        enable = false
        siteID = ""
        limit = 5
        height = ""
        color = ""
        colorful = true
        dislikes = false
        outlined = false
      #  Commento è¯„è®ºç³»ç»Ÿè®¾ç½®
      [params.page.comment.commento]
        enable = false
      #  utterances è¯„è®ºç³»ç»Ÿè®¾ç½®
      [params.page.comment.utterances]
        enable = false
        # owner/repo
        repo = "deequoique/deequoique.github.io"
        issueTerm = "title"
        label = ""
        lightTheme = "github-light"
        darkTheme = "github-dark"
      # giscus comment è¯„è®ºç³»ç»Ÿè®¾ç½® (https://giscus.app/zh-CN)
      [params.page.comment.giscus]
        enable = true
        repo = "deequoique/deequoique.github.io"
        repoId = "R_kgDOK8AUew"
        category = "Announcements"
        categoryId = "DIC_kwDOK8AUe84CiX5r"
        mapping = "pathname"
        origin = "https://giscus.app" # FixIt NEW | 0.3.7 Or set it to your self-hosted domain
        strict = "0" # FixIt NEW | 0.2.18
        term = ""
        reactionsEnabled = "1"
        emitMetadata = "0"
        inputPosition = "top" # ["top", "bottom"]
        lang = "zh-CN"
        lightTheme = "light"
        darkTheme = "dark"
        lazyLoad = true
    #  ç¬¬ä¸‰æ–¹åº“é…ç½®
    [params.page.library]
      [params.page.library.css]
        # someCSS = "some.css"
        # ä½äº "assets/"
        # æˆ–è€…
        # someCSS = "https://cdn.example.com/some.css"
      [params.page.library.js]
        someJavascript = "/js/custom.js"
        # ä½äº "assets/"
        # æˆ–è€…
        # someJavascript = "https://cdn.example.com/some.js"
    #  é¡µé¢ SEO é…ç½®
    [params.page.seo]
      # å›¾ç‰‡ URL
      images = []
      # å‡ºç‰ˆè€…ä¿¡æ¯
      [params.page.seo.publisher]
        name = ""
        logoUrl = ""

  #  TypeIt é…ç½®
  [params.typeit]
    # æ¯ä¸€æ­¥çš„æ‰“å­—é€Ÿåº¦ (å•ä½æ˜¯æ¯«ç§’)
    speed = 100
    # å…‰æ ‡çš„é—ªçƒé€Ÿåº¦ (å•ä½æ˜¯æ¯«ç§’)
    cursorSpeed = 1000
    # å…‰æ ‡çš„å­—ç¬¦ (æ”¯æŒ HTML æ ¼å¼)
    cursorChar = "|"
    # æ‰“å­—ç»“æŸä¹‹åå…‰æ ‡çš„æŒç»­æ—¶é—´ (å•ä½æ˜¯æ¯«ç§’, "-1" ä»£è¡¨æ— é™å¤§)
    duration = -1

  # ç½‘ç«™éªŒè¯ä»£ç ï¼Œç”¨äº Google/Bing/Yandex/Pinterest/Baidu
  [params.verification]
    google = ""
    bing = ""
    yandex = ""
    pinterest = ""
    baidu = ""

  #  ç½‘ç«™ SEO é…ç½®
  [params.seo]
    # å›¾ç‰‡ URL
    image = ""
    # ç¼©ç•¥å›¾ URL
    thumbnailUrl = ""

  #  ç½‘ç«™åˆ†æé…ç½®
  [params.analytics]
    enable = true
    # Google Analytics
    [params.analytics.google]
      id = "G-02P8GHNTFV"
      # æ˜¯å¦åŒ¿ååŒ–ç”¨æˆ· IP
      anonymizeIP = true
    # Fathom Analytics
    [params.analytics.fathom]
      id = ""
      # è‡ªè¡Œæ‰˜ç®¡è¿½è¸ªå™¨æ—¶çš„ä¸»æœºè·¯å¾„
      server = ""
    # Plausible Analytics
    [params.analytics.plausible]
      dataDomain = ""
    # Yandex Metrica
    [params.analytics.yandexMetrica]
      id = ""

  #  Cookie è®¸å¯é…ç½®
  [params.cookieconsent]
    enable = false
    # ç”¨äº Cookie è®¸å¯æ¨ªå¹…çš„æ–‡æœ¬å­—ç¬¦ä¸²
    [params.cookieconsent.content]
      message = ""
      dismiss = ""
      link = ""

  #  ç¬¬ä¸‰æ–¹åº“æ–‡ä»¶çš„ CDN è®¾ç½®
  [params.cdn]
    # CDN æ•°æ®æ–‡ä»¶åç§°, é»˜è®¤ä¸å¯ç”¨
    # ["jsdelivr.yml"]
    # ä½äº "themes/LoveIt/assets/data/cdn/" ç›®å½•
    # å¯ä»¥åœ¨ä½ çš„é¡¹ç›®ä¸‹ç›¸åŒè·¯å¾„å­˜æ”¾ä½ è‡ªå·±çš„æ•°æ®æ–‡ä»¶:
    # "assets/data/cdn/"
    data = "jquery.yml"

  #  å…¼å®¹æ€§è®¾ç½®
  [params.compatibility]
    # æ˜¯å¦ä½¿ç”¨ Polyfill.io æ¥å…¼å®¹æ—§å¼æµè§ˆå™¨
    polyfill = false
    # æ˜¯å¦ä½¿ç”¨ object-fit-images æ¥å…¼å®¹æ—§å¼æµè§ˆå™¨
    objectFit = false

# Hugo è§£ææ–‡æ¡£çš„é…ç½®
[markup]
  _merge = "shallow"

# ç½‘ç«™åœ°å›¾é…ç½®
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks é…ç½®
[Permalinks]
  # posts = ":year/:month/:filename"
  posts = ":filename"

# éšç§ä¿¡æ¯é…ç½®
[privacy]
  #  Google Analytics ç›¸å…³éšç§ (è¢« params.analytics.google æ›¿ä»£)
  [privacy.googleAnalytics]
    # ...
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

# ç”¨äºè¾“å‡º Markdown æ ¼å¼æ–‡æ¡£çš„è®¾ç½®
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# ç”¨äºè¾“å‡º Markdown æ ¼å¼æ–‡æ¡£çš„è®¾ç½®
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# ç”¨äº Hugo è¾“å‡ºæ–‡æ¡£çš„è®¾ç½®
[outputs]
  _merge = "shallow"

[taxonomies]
  _merge = "shallow"